name: release

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Set-up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: gradle

      # TODO - name: Remove SNAPSHOT and prepare for release

      - name: Build with Gradle
        run: ./gradlew assembleRelease uploadArchives
        env:
          ORG_GRADLE_PROJECT_NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_SIGNING_KEY: ${{ secrets.GPG_SIGNATURE_KEY }}
          ORG_GRADLE_PROJECT_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNATURE_PASSWORD }}

      # TODO - name: Create GH Release and Tag

      # TODO - name: Update version to next minor SNAPSHOT
